apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: olmo-2-1124-7b-instruct
spec:
  runtime:
    name: srt-olmo-2-1124-7b-instruct
  model:
    name: olmo-2-1124-7b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
