apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: telechat2-35b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: teleai
  disabled: false
  version: "1.0.0"
  displayName: teleai.telechat2-35b
  storage:
    storageUri: hf://TeleAI/TeleChat2-35B
    path: /raid/models/teleai/telechat2-35b
