apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: solar-10-7b-instruct-v1-0
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: upstage
  displayName: upstage.solar-10.7b-instruct-v1.0
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://upstage/SOLAR-10.7B-Instruct-v1.0
    path: /raid/models/upstage/SOLAR-10.7B-Instruct-v1.0
    key: "hf-token"
