apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: granite-3-0-3b-a800m-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: ibm-granite
  displayName: ibm-granite.granite-3.0-3b-a800m-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://ibm-granite/granite-3.0-3b-a800m-instruct
    path: /raid/models/ibm-granite/granite-3.0-3b-a800m-instruct
