apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: granite-3-1-8b-instruct-test
  namespace: granite-3-1-8b-instruct-test
spec:
  model:
    name: granite-3-1-8b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-granite-3-1-8b-instruct
  router:
    minReplicas: 1
    maxReplicas: 1
