apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internlm2-20b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: internlm
  disabled: false
  version: "1.0.0"
  displayName: internlm.internlm2-20b
  storage:
    storageUri: hf://internlm/internlm2-20b
    path: /raid/models/internlm/internlm2-20b
