apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internlm2-1-8b-reward
spec:
  modelCapabilities:
    - REWARD_SCORING
  vendor: internlm
  disabled: false
  version: "1.0.0"
  displayName: internlm.internlm2-1.8b-reward
  storage:
    storageUri: hf://internlm/internlm2-1_8b-reward
    path: /raid/models/internlm/internlm2-1.8b-reward
