apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internlm3-8b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: internlm
  disabled: false
  version: "1.0.0"
  displayName: internlm.internlm3-8b-instruct
  storage:
    storageUri: hf://internlm/internlm3-8b-instruct
    path: /raid/models/internlm/internlm3-8b-instruct
