apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internlm-chat-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: internlm
  disabled: false
  version: "1.0.0"
  displayName: internlm.internlm-chat-7b
  storage:
    storageUri: hf://internlm/internlm-chat-7b
    path: /raid/models/internlm/internlm-chat-7b
