apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: all-roberta-large-v1
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  vendor: sentence-transformers
  disabled: false
  version: "1.0.0"
  displayName: sentence-transformers.all-roberta-large-v1
  storage:
    storageUri: hf://sentence-transformers/all-roberta-large-v1
    path: /raid/models/sentence-transformers/all-roberta-large-v1
