apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: baichuan2-7b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: baichuan
  disabled: false
  version: "1.0.0"
  displayName: baichuan.baichuan2-7b-chat
  storage:
    storageUri: hf://baichuan-inc/Baichuan2-7B-Chat
    path: /raid/models/baichuan/baichuan2-7b-chat
