apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: baichuan2-13b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: baichuan-inc
  displayName: baichuan-inc.baichuan2-13b-chat
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://baichuan-inc/Baichuan2-13B-Chat
    path: /raid/models/baichuan-inc/Baichuan2-13B-Chat
