apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: ultravox-v0-3
spec:
  modelCapabilities:
    - AUDIO_TO_TEXT
    - TEXT_TO_TEXT
  vendor: fixie-ai
  disabled: false
  version: "1.0.0"
  displayName: fixie-ai.ultravox-v0.3
  storage:
    storageUri: hf://fixie-ai/ultravox-v0_3
    path: /raid/models/fixie-ai/ultravox-v0.3
