apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-7b-instruct-embed-base
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  vendor: ssmits
  disabled: false
  version: "1.0.0"
  displayName: ssmits.qwen2-7b-instruct-embed-base
  storage:
    storageUri: hf://ssmits/Qwen2-7B-Instruct-embed-base
    path: /raid/models/ssmits/qwen2-7b-instruct-embed-base
