apiVersion: ome.io/v1beta1
kind: DedicatedAIClusterProfile
metadata:
  name: large-h100-count-one
spec:
  count: 1
  resources:
    limits:
      cpu: 160
      memory: 520Gi
      nvidia.com/gpu: 8
    requests:
      cpu: 160
      memory: 520Gi
      nvidia.com/gpu: 8
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beta.kubernetes.io/instance-type
                operator: In
                values:
                  - BM.GPU.H100.8
