apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mantis-8b-siglip-llama3
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: tiger-lab
  disabled: false
  version: "1.0.0"
  displayName: tiger-lab.mantis-8b-siglip-llama3
  storage:
    storageUri: hf://TIGER-Lab/Mantis-8B-siglip-llama3
    path: /raid/models/tiger-lab/mantis-8b-siglip-llama3
