apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-neox-20b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: eleutherai
  disabled: false
  version: "1.0.0"
  displayName: eleutherai.gpt-neox-20b
  storage:
    storageUri: hf://EleutherAI/gpt-neox-20b
    path: /raid/models/eleutherai/gpt-neox-20b
