apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: pythia-12b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: eleutherai
  disabled: false
  version: "1.0.0"
  displayName: eleutherai.pythia-12b
  storage:
    storageUri: hf://EleutherAI/pythia-12b
    path: /raid/models/eleutherai/pythia-12b
