apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-2-90b-vision-instruct
spec:
  displayName: meta.llama-3.2-90b-vision-instruct
  vendor: meta
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://meta-llama/Llama-3.2-90B-Vision-Instruct
    path: /raid/models/meta/llama-3-2-90b-vision-instruct
    key: "hf-token"