apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-405b-instruct-fp8
spec:
  vendor: meta
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://meta-llama/Llama-3.1-405B-Instruct-FP8
    path: /raid/models/meta/Llama-3.1-405B-Instruct-FP8
    key: "hf-token"
