apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-8b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-3.1-8b-instruct
  storage:
    storageUri: hf://meta-llama/Llama-3.1-8B-Instruct
    path: /raid/models/meta/llama-3-1-8b-instruct