apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-70b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-3.1-70b-instruct
  storage:
    storageUri: hf://meta-llama/Meta-Llama-3.1-70B-Instruct
    path: /raid/models/meta/llama-3-1-70b-instruct
    key: "hf-token"