apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-70b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  disabled: false
  displayName: meta.llama-3-70b-instruct
  storage:
    storageUri: hf://meta-llama/Meta-Llama-3-70B-Instruct
    path: /raid/models/meta/llama-3-70b-instruct
    key: "hf-token"
  vendor: meta
  version: "1.0.0"