apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-2-1b-instruct
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: "vllm-llama-3-2-1b-instruct"
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "false"
    models.ome.io/internal: "true"
    models.ome.io/lifecycle-phase: "ACTIVE"
spec:
  displayName: meta.llama-3.2-1b-instruct
  vendor: meta
  disabled: false
  version: "1.0.0"
  compartmentID: ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva
  modelFramework:
    name: transformers
    version: "4.45.0.dev0"
  modelFormat:
    name: safetensors
    version: "1"
  modelArchitecture: LlamaForCausalLM
  modelParameterSize: 1B
  modelCapabilities:
    - "CHAT"
  storage:
    storageUri: oci://n/idqj093njucb/b/model-store/o/meta/llama-3-2-1b-instruct
    path: /raid/models/meta/Llama-3.2-1B-Instruct
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                  - BM.GPU.H100.8
                  - BM.GPU4.8
                  - BM.GPU.A100-v2.8
  maxTokens: 131072
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: SMALL_GENERIC_V2
          quotaUnit: 1
          default: true
  modelConfiguration:
    {
      "architectures": [
        "LlamaForCausalLM"
      ],
      "attention_bias": false,
      "attention_dropout": 0.0,
      "bos_token_id": 128000,
      "eos_token_id": [
        128001,
        128008,
        128009
      ],
      "head_dim": 64,
      "hidden_act": "silu",
      "hidden_size": 2048,
      "initializer_range": 0.02,
      "intermediate_size": 8192,
      "max_position_embeddings": 131072,
      "mlp_bias": false,
      "model_type": "llama",
      "num_attention_heads": 32,
      "num_hidden_layers": 16,
      "num_key_value_heads": 8,
      "pretraining_tp": 1,
      "rms_norm_eps": 1e-05,
      "rope_scaling": {
        "factor": 32.0,
        "high_freq_factor": 4.0,
        "low_freq_factor": 1.0,
        "original_max_position_embeddings": 8192,
        "rope_type": "llama3"
      },
      "rope_theta": 500000.0,
      "tie_word_embeddings": true,
      "torch_dtype": "bfloat16",
      "transformers_version": "4.45.0.dev0",
      "use_cache": true,
      "vocab_size": 128256
    }