# This model is gated on HuggingFace
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-guard-3-8b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-guard-3-8b
  storage:
    storageUri: hf://meta-llama/Llama-Guard-3-8B
    path: /raid/models/meta/llama-guard-3-8b
    key: "hf-token"
