# This model is gated on HuggingFace
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-2-13b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-2-13b
  storage:
    storageUri: hf://meta-llama/Llama-2-13b-hf
    path: /raid/models/meta/llama-2-13b
    key: "hf-token"
