apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-3-70b-instruct-fp8-dynamic
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  disabled: false
  displayName: meta.llama-3.3-70b-instruct-fp8-dynamic
  storage:
    storageUri: hf://RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
    path: /raid/models/meta/llama-3-3-70b-instruct-fp8-dynamic
    key: "hf-token"
  vendor: meta
  version: "1.0.0"