# This model is gated on HuggingFace
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-2-3b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  displayName: meta.llama-3.2-3b-instruct
  vendor: meta
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://meta-llama/Llama-3.2-3B-Instruct
    path: /raid/models/meta/llama-3-2-3b-instruct
    key: "hf-token"