# This model is gated on HuggingFace
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-2-70b-chat-hf
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-2-70b-chat-hf
  storage:
    storageUri: hf://meta-llama/Llama-2-70b-chat-hf
    path: /raid/models/meta/llama-2-70b-chat-hf
    key: "hf-token"
