apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: dse-qwen2-2b-mrl-v1
spec:
  modelCapabilities:
    - IMAGE_TO_EMBEDDING
    - TEXT_TO_EMBEDDING
  vendor: mrlight
  disabled: false
  version: "1.0.0"
  displayName: mrlight.dse-qwen2-2b-mrl-v1
  storage:
    storageUri: hf://MrLight/dse-qwen2-2b-mrl-v1
    path: /raid/models/mrlight/dse-qwen2-2b-mrl-v1
