# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: stablelm-tuned-alpha-7b
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: stablelm-tuned-alpha-7b
  namespace: stablelm-tuned-alpha-7b
spec:
  model:
    name: stablelm-tuned-alpha-7b
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-stablelm-tuned-alpha-7b
  router:
    minReplicas: 1
    maxReplicas: 1
