apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gemma-3-1b-it
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
    - IMAGE_TEXT_TO_TEXT
  vendor: google
  displayName: google.gemma-3-1b-it
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://google/gemma-3-1b-it
    path: /raid/models/google/gemma-3-1b-it
    key: hf-token
