apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: paligemma-3b-mix-224
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: google
  disabled: false
  version: "1.0.0"
  displayName: google.paligemma-3b-mix-224
  storage:
    storageUri: hf://google/paligemma-3b-mix-224
    path: /raid/models/google/paligemma-3b-mix-224
