apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# SRT runtimes
- srt/deepseek-rdma-pd-rt.yaml
- srt/deepseek-rdma-rt.yaml
- srt/e5-mistral-7b-instruct-rt.yaml
- srt/gpt-oss-120b-rt.yaml
- srt/gpt-oss-20b-rt.yaml
- srt/kimi-k2-pd-rt.yaml
- srt/meta/llama-3-1-70b-instruct-pd-rt.yaml
- srt/meta/llama-3-1-70b-instruct-rt.yaml
- srt/meta/llama-3-1-8b-instruct-grpc-rt.yaml
- srt/meta/llama-3-1-8b-instruct-rt.yaml
- srt/meta/llama-3-2-11b-vision-instruct-rt.yaml
- srt/meta/llama-3-2-1b-instruct-pd-rt.yaml
- srt/meta/llama-3-2-1b-instruct-rt.yaml
- srt/meta/llama-3-2-3b-instruct-pd-rt.yaml
- srt/meta/llama-3-2-3b-instruct-rt.yaml
- srt/meta/llama-3-2-90b-vision-instruct-rt.yaml
- srt/meta/llama-3-3-70b-instruct-fp8-dynamic-rt.yaml
- srt/meta/llama-3-3-70b-instruct-pd-rt.yaml
- srt/meta/llama-3-3-70b-instruct-rt.yaml
- srt/meta/llama-4-maverick-17b-128e-instruct-fp8-grpc-rt.yaml
- srt/meta/llama-4-maverick-17b-128e-instruct-fp8-pd-grpc-rt.yaml
- srt/meta/llama-4-maverick-17b-128e-instruct-fp8-pd-rt.yaml
- srt/meta/llama-4-maverick-17b-128e-instruct-fp8-rt.yaml
- srt/meta/llama-4-scout-17b-16e-instruct-pd-rt.yaml
- srt/meta/llama-4-scout-17b-16e-instruct-rt.yaml
- srt/mistral-7b-instruct-pd-rt.yaml
- srt/mistral-7b-instruct-rt.yaml
- srt/mixtral-8x7b-instruct-pd-rt.yaml
- srt/mixtral-8x7b-instruct-rt.yaml
# vLLM runtimes
- vllm/e5-mistral-7b-instruct-rt.yaml
- vllm/llama-3-1-405b-instruct-fp8-rt.yaml
- vllm/llama-3-1-8b-instruct-rt.yaml
- vllm/llama-3-1-nemotron-nano-8b-v1-rt.yaml
- vllm/llama-3-1-nemotron-ultra-253b-v1-rt.yaml
- vllm/llama-3-2-11b-vision-instruct-rt.yaml
- vllm/llama-3-2-1b-instruct-rt.yaml
- vllm/llama-3-2-3b-instruct-rt.yaml
- vllm/llama-3-2-90b-vision-instruct-fp8-dynamic-rt.yaml
- vllm/llama-3-2-90b-vision-instruct-rt.yaml
- vllm/llama-3-3-70b-instruct-fp8-dynamic-rt.yaml
- vllm/llama-3-3-70b-instruct-rt.yaml
- vllm/llama-3-3-nemotron-super-49b-v1-rt.yaml
- vllm/llama-4-maverick-17b-128e-instruct-fp8-rt.yaml
- vllm/llama-4-scout-17b-16e-instruct-rt.yaml
- vllm/mistral-7b-instruct-rt.yaml
- vllm/mixtral-8x7b-instruct-rt.yaml
