apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internvl2-5-4b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: opengvlab
  disabled: false
  version: "1.0.0"
  displayName: opengvlab.internvl2.5-4b
  storage:
    storageUri: hf://OpenGVLab/InternVL2_5-4B
    path: /raid/models/opengvlab/internvl2.5-4b
