apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: internvl2-5-8b
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: OpenGVLab
  displayName: opengvlab.internvl2.5-8b
  disabled: false
  version: "1.0.0"
  modelArchitecture: InternVLChatModel
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.37.2"
  modelParameterSize: 8B
  storage:
    storageUri: hf://OpenGVLab/InternVL2_5-8B
    path: /raid/models/OpenGVLab/InternVL2_5-8B
    key: "hf-token"
