apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mono-internvl-2b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: opengvlab
  disabled: false
  version: "1.0.0"
  displayName: opengvlab.mono-internvl-2b
  storage:
    storageUri: hf://OpenGVLab/Mono-InternVL-2B
    path: /raid/models/opengvlab/mono-internvl-2b
