apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # adept
  - adept/persimmon-8b-chat.yaml

  # Alibaba-NLP
  - Alibaba-NLP/gme-Qwen2-VL-2B-Instruct.yaml
  - Alibaba-NLP/gte-Qwen2-7B-instruct.yaml

  # allenai
  - allenai/OLMo-2-1124-7B-Instruct.yaml
  - allenai/OLMoE-1B-7B-0924.yaml

  # arcee-ai
  - arcee-ai/AFM-4.5B-Base.yaml

  # BAAI
  - BAAI/bge-large-en-v1.5.yaml
  - BAAI/bge-reranker-v2-m3.yaml

  # baichuan-inc
  - baichuan-inc/Baichuan2-13B-Chat.yaml

  # baidu
  - baidu/ERNIE-4.5-21B-A3B-PT.yaml

  # bigcode
  - bigcode/starcoder2-7b.yaml

  # CofeAI
  - CofeAI/Tele-FLM.yaml

  # CohereForAI
  - CohereForAI/c4ai-command-r-v01.yaml

  # databricks
  - databricks/dbrx-instruct.yaml

  # deepseek-ai
  - deepseek-ai/DeepSeek-R1.yaml
  - deepseek-ai/DeepSeek-V3-0324.yaml
  - deepseek-ai/DeepSeek-V3.yaml
  - deepseek-ai/deepseek-vl2.yaml
  - deepseek-ai/Janus-Pro-7B.yaml

  # Efficient-Large-Model
  - Efficient-Large-Model/NVILA-8B.yaml

  # google
  - google/gemma-3-1b-it.yaml
  - google/gemma-3-4b-it.yaml

  # HuggingFaceTB
  - HuggingFaceTB/SmolLM-1.7B.yaml

  # ibm-granite
  - ibm-granite/granite-3.0-3b-a800m-instruct.yaml
  - ibm-granite/granite-3.1-8b-instruct.yaml

  # inclusionAI
  - inclusionAI/Ling-lite.yaml
  - inclusionAI/Ling-plus.yaml

  # internlm
  - internlm/internlm2-7b.yaml

  # intfloat
  - intfloat/e5-mistral-7b-instruct.yaml

  # jet-ai
  - jet-ai/Jet-Nemotron-2B.yaml

  # LGAI-EXAONE
  - LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct.yaml

  # liuhaotian
  - liuhaotian/llava-v1.5-13b.yaml

  # lmms-lab
  - lmms-lab/llava-next-72b.yaml
  - lmms-lab/llava-onevision-qwen2-7b-ov.yaml

  # lmsys
  - lmsys/gpt-oss-120b.yaml
  - lmsys/gpt-oss-20b.yaml

  # meta
  - meta/Llama-3-70B-Instruct.yaml
  - meta/Llama-3.1-405B-Instruct-FP8.yaml
  - meta/Llama-3.1-70B-Instruct.yaml
  - meta/Llama-3.1-8B-Instruct.yaml
  - meta/Llama-3.2-11B-Vision-Instruct.yaml
  - meta/Llama-3.2-1B-Instruct.yaml
  - meta/Llama-3.2-3B-Instruct.yaml
  - meta/Llama-3.2-90B-Vision-Instruct-FP8.yaml
  - meta/Llama-3.2-90B-Vision-Instruct.yaml
  - meta/Llama-3.3-70B-Instruct-FP8-dynamic.yaml
  - meta/Llama-3.3-70B-instruct.yaml
  - meta/Llama-4-Maverick-17B-128E-Instruct-FP8.yaml
  - meta/Llama-4-Maverick-17B-128E-Instruct.yaml
  - meta/Llama-4-Scout-17B-16E-Instruct.yaml

  # microsoft
  - microsoft/Phi-3-vision-128k-instruct.yaml
  - microsoft/Phi-3.5-MoE-instruct.yaml
  - microsoft/Phi-4-multimodal-instruct.yaml

  # minimax
  - minimax/MiniMax-M2.yaml

  # mistralai
  - mistralai/Mistral-7B-Instruct-v0.2.yaml
  - mistralai/Mistral-Small-3.1-24B-Instruct-2503.yaml

  # moonshotai
  - moonshotai/Kimi-K2-Instruct.yaml
  - moonshotai/Kimi-VL-A3B-Instruct.yaml

  # nvidia
  - nvidia/Llama-3_1-Nemotron-Ultra-253B-v1.yaml
  - nvidia/Llama-3_3-Nemotron-Super-49B-v1.yaml
  - nvidia/Llama-3.1-Nemotron-Nano-8B-v1.yaml
  - nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16.yaml
  - nvidia/NVIDIA-Nemotron-Nano-9B-v2.yaml

  # openai
  - openai/clip-vit-large-patch14-336.yaml
  - openai/gpt-oss-120b.yaml
  - openai/gpt-oss-20b.yaml

  # openbmb
  - openbmb/MiniCPM-V-2_6.yaml
  - openbmb/MiniCPM3-4B.yaml

  # OrionStarAI
  - OrionStarAI/Orion-14B-Base.yaml

  # Qwen
  - Qwen/Qwen3-0.6B.yaml
  - Qwen/Qwen3-30B-A3B.yaml
  - Qwen/Qwen3-Embedding-0.6B.yaml
  - Qwen/Qwen3-Embedding-4B.yaml
  - Qwen/Qwen3-Next-80B-A3B-Instruct.yaml
  - Qwen/Qwen3-VL-235B-A22B-Instruct.yaml

  # rednote-hilab
  - rednote-hilab/dots.ocr.yaml
  - rednote-hilab/dots.vlm1.inst.yaml

  # stabilityai
  - stabilityai/stablelm-tuned-alpha-7b.yaml

  # THUDM
  - THUDM/chatglm2-6b.yaml

  # upstage
  - upstage/SOLAR-10.7B-Instruct-v1.0.yaml

  # xai-org
  - xai-org/grok-1.yaml

  # XiaomiMiMo
  - XiaomiMiMo/MiMo-7B-RL.yaml
  - XiaomiMiMo/MiMo-VL-7B-RL.yaml

  # xverse
  - xverse/XVERSE-MoE-A36B.yaml

  # zai-org
  - zai-org/GLM-4.5V.yaml

  # ZhipuAI
  - ZhipuAI/glm-4-9b-chat.yaml
