apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 01-ai
  - 01-ai/Yi-34B.yaml

  # adept
  - adept/fuyu-8b.yaml
  - adept/persimmon-8b-chat.yaml

  # ai21labs
  - ai21labs/AI21-Jamba-1.5-Large.yaml
  - ai21labs/AI21-Jamba-1.5-Mini.yaml
  - ai21labs/Jamba-tiny-reward-dev.yaml
  - ai21labs/Jamba-v0.1.yaml

  # Alibaba-NLP
  - Alibaba-NLP/gme-Qwen2-VL-2B-Instruct.yaml
  - Alibaba-NLP/gte-Qwen2-7B-instruct.yaml

  # allenai
  - allenai/Molmo-72B-0924.yaml
  - allenai/Molmo-7B-D-0924.yaml
  - allenai/OLMo-1B-hf.yaml
  - allenai/OLMo-2-1124-7B-Instruct.yaml
  - allenai/OLMo-7B-hf.yaml
  - allenai/OLMo2-7B-1124.yaml
  - allenai/OLMoE-1B-7B-0924.yaml

  # arcee-ai
  - arcee-ai/AFM-4.5B-Base.yaml

  # BAAI
  - BAAI/Aquila-7B.yaml
  - BAAI/AquilaChat-7B.yaml
  - BAAI/bge-base-en-v1.5.yaml
  - BAAI/bge-large-en-v1.5.yaml
  - BAAI/bge-m3.yaml
  - BAAI/bge-multilingual-gemma2.yaml
  - BAAI/bge-reranker-v2-m3.yaml

  # baichuan-inc
  - baichuan-inc/Baichuan2-13B-Chat.yaml
  - baichuan-inc/Baichuan2-7B-Chat.yaml

  # baidu
  - baidu/ERNIE-4.5-21B-A3B-PT.yaml

  # bigcode
  - bigcode/gpt_bigcode-santacoder.yaml
  - bigcode/starcoder.yaml
  - bigcode/starcoder2-15b.yaml
  - bigcode/starcoder2-3b.yaml
  - bigcode/starcoder2-7b.yaml

  # bigscience
  - bigscience/bloom.yaml
  - bigscience/bloomz.yaml

  # CofeAI
  - CofeAI/Tele-FLM.yaml

  # CohereForAI
  - CohereForAI/c4ai-command-r-v01.yaml
  - CohereForAI/c4ai-command-r7b-12-2024.yaml

  # cross-encoder
  - cross-encoder/ms-marco-MiniLM-L-6-v2.yaml
  - cross-encoder/quora-roberta-base.yaml

  # databricks
  - databricks/dbrx-instruct.yaml
  - databricks/dolly-v2-12b.yaml

  # Deci
  - Deci/DeciLM-7B-instruct.yaml
  - Deci/DeciLM-7B.yaml

  # deepseek-ai
  - deepseek-ai/deepseek-llm-67b-base.yaml
  - deepseek-ai/deepseek-llm-7b-chat.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Llama-70B.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Llama-8B.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Qwen-14B.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Qwen-32B.yaml
  - deepseek-ai/DeepSeek-R1-Distill-Qwen-7B.yaml
  - deepseek-ai/DeepSeek-R1-Zero.yaml
  - deepseek-ai/DeepSeek-R1.yaml
  - deepseek-ai/DeepSeek-V2.5.yaml
  - deepseek-ai/DeepSeek-V2.yaml
  - deepseek-ai/DeepSeek-V3-0324.yaml
  - deepseek-ai/DeepSeek-V3.yaml
  - deepseek-ai/deepseek-vl2-small.yaml
  - deepseek-ai/deepseek-vl2-tiny.yaml
  - deepseek-ai/deepseek-vl2.yaml
  - deepseek-ai/Janus-Pro-7B.yaml

  # Efficient-Large-Model
  - Efficient-Large-Model/NVILA-8B.yaml

  # EleutherAI
  - EleutherAI/gpt-j-6b.yaml
  - EleutherAI/gpt-neox-20b.yaml
  - EleutherAI/pythia-12b.yaml

  # facebook
  - facebook/bart-base.yaml
  - facebook/bart-large-cnn.yaml
  - facebook/chameleon-7b.yaml
  - facebook/opt-66b.yaml
  - facebook/opt-iml-max-30b.yaml

  # fixie-ai
  - fixie-ai/ultravox-v0_3.yaml

  # google
  - google/gemma-2-27b.yaml
  - google/gemma-2-2b.yaml
  - google/gemma-2-9b.yaml
  - google/gemma-2b.yaml
  - google/gemma-3-12b-it.yaml
  - google/gemma-3-1b-it.yaml
  - google/gemma-3-27b-it.yaml
  - google/gemma-3-4b-it.yaml
  - google/gemma-7b.yaml
  - google/paligemma-3b-mix-224.yaml
  - google/paligemma-3b-pt-224.yaml
  - google/paligemma2-3b-ft-docci-448.yaml

  # h2oai
  - h2oai/h2ovl-mississippi-2b.yaml
  - h2oai/h2ovl-mississippi-800m.yaml

  # HuggingFaceM4
  - HuggingFaceM4/Idefics3-8B-Llama3.yaml

  # HuggingFaceTB
  - HuggingFaceTB/SmolLM-1.7B.yaml
  - HuggingFaceTB/SmolLM-135M.yaml
  - HuggingFaceTB/SmolLM-360M.yaml

  # ibm-granite
  - ibm-granite/granite-3.0-2b-instruct.yaml
  - ibm-granite/granite-3.0-3b-a800m-instruct.yaml
  - ibm-granite/granite-3.0-8b-instruct.yaml
  - ibm-granite/granite-3.1-2b-instruct.yaml
  - ibm-granite/granite-3.1-8b-instruct.yaml

  # inceptionai
  - inceptionai/jais-13b.yaml
  - inceptionai/jais-30b-v3.yaml

  # inclusionAI
  - inclusionAI/Ling-lite.yaml
  - inclusionAI/Ling-plus.yaml

  # internlm
  - internlm/internlm-7b.yaml
  - internlm/internlm-chat-7b.yaml
  - internlm/internlm2-1_8b-reward.yaml
  - internlm/internlm2-20b.yaml
  - internlm/internlm2-7b-reward.yaml
  - internlm/internlm2-7b.yaml
  - internlm/internlm3-8b-instruct.yaml

  # intfloat
  - intfloat/e5-mistral-7b-instruct.yaml
  - intfloat/multilingual-e5-large.yaml

  # jason9693
  - jason9693/Qwen2.5-1.5B-apeach.yaml

  # jet-ai
  - jet-ai/Jet-Nemotron-2B.yaml

  # LGAI-EXAONE
  - LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct.yaml

  # liuhaotian
  - liuhaotian/llava-v1.5-13b.yaml
  - liuhaotian/llava-v1.5-7b.yaml
  - liuhaotian/llava-v1.6-vicuna-13b.yaml
  - liuhaotian/llava-v1.6-vicuna-7b.yaml

  # llava-hf
  - llava-hf/llava-1.5-7b-hf.yaml
  - llava-hf/LLaVA-NeXT-Video-7B-hf.yaml
  - llava-hf/llava-onevision-qwen2-0.5b-ov-hf.yaml
  - llava-hf/llava-v1.6-mistral-7b-hf.yaml

  # lmms-lab
  - lmms-lab/llava-next-72b.yaml
  - lmms-lab/llava-next-8b.yaml
  - lmms-lab/llava-onevision-qwen2-7b-ov.yaml

  # lmsys
  - lmsys/gpt-oss-120b.yaml
  - lmsys/gpt-oss-20b.yaml

  # meta
  - meta/Llama-2-13b-hf.yaml
  - meta/Llama-2-70b-hf.yaml
  - meta/Llama-2-7b-hf.yaml
  - meta/Llama-3-70B-Instruct.yaml
  - meta/Llama-3.1-405B-Instruct-FP8.yaml
  - meta/Llama-3.1-70B-Instruct.yaml
  - meta/Llama-3.1-8B-Instruct.yaml
  - meta/Llama-3.2-11B-Vision-Instruct.yaml
  - meta/Llama-3.2-1B-Instruct.yaml
  - meta/Llama-3.2-3B-Instruct.yaml
  - meta/Llama-3.2-90B-Vision-Instruct-FP8.yaml
  - meta/Llama-3.2-90B-Vision-Instruct.yaml
  - meta/Llama-3.3-70B-Instruct-FP8-dynamic.yaml
  - meta/Llama-3.3-70B-instruct.yaml
  - meta/Llama-4-Maverick-17B-128E-Instruct-FP8.yaml
  - meta/Llama-4-Maverick-17B-128E-Instruct.yaml
  - meta/Llama-4-Scout-17B-16E-Instruct.yaml
  - meta/Meta-Llama-3-8B-Instruct.yaml

  # microsoft
  - microsoft/phi-1_5.yaml
  - microsoft/phi-2.yaml
  - microsoft/Phi-3-medium-4k-instruct.yaml
  - microsoft/Phi-3-mini-128k-instruct.yaml
  - microsoft/Phi-3-mini-4k-instruct.yaml
  - microsoft/Phi-3-small-8k-instruct.yaml
  - microsoft/Phi-3-vision-128k-instruct.yaml
  - microsoft/Phi-3.5-mini-instruct.yaml
  - microsoft/Phi-3.5-MoE-instruct.yaml
  - microsoft/Phi-3.5-vision-instruct.yaml
  - microsoft/Phi-4-multimodal-instruct.yaml
  - microsoft/phi-4.yaml

  # minimax
  - minimax/MiniMax-M2.yaml

  # mistralai
  - mistralai/Mistral-7B-Instruct-v0.2.yaml
  - mistralai/Mistral-7B-Instruct-v0.3.yaml
  - mistralai/Mistral-7B-v0.1.yaml
  - mistralai/Mistral-Nemo-Instruct-2407.yaml
  - mistralai/Mistral-Small-3.1-24B-Instruct-2503.yaml
  - mistralai/Mixtral-8x22B-v0.1.yaml
  - mistralai/Mixtral-8x7B-Instruct-v0.1.yaml
  - mistralai/Mixtral-8x7B-v0.1.yaml
  - mistralai/Pixtral-12B-2409.yaml

  # moonshotai
  - moonshotai/Kimi-K2-Instruct.yaml
  - moonshotai/Kimi-VL-A3B-Instruct.yaml

  # mosaicml
  - mosaicml/mpt-30b.yaml
  - mosaicml/mpt-7b.yaml

  # MrLight
  - MrLight/dse-qwen2-2b-mrl-v1.yaml

  # nvidia
  - nvidia/Llama-3_1-Nemotron-Ultra-253B-v1.yaml
  - nvidia/Llama-3_3-Nemotron-Super-49B-v1.yaml
  - nvidia/Llama-3.1-Nemotron-Nano-8B-v1.yaml
  - nvidia/Minitron-8B-Base.yaml
  - nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16.yaml
  - nvidia/NVIDIA-Nemotron-Nano-9B-v2.yaml
  - nvidia/NVLM-D-72B.yaml

  # openai
  - openai/clip-vit-large-patch14-336.yaml
  - openai/gpt-oss-120b.yaml
  - openai/gpt-oss-20b.yaml

  # openbmb
  - openbmb/MiniCPM-2B-sft-bf16.yaml
  - openbmb/MiniCPM-Llama3-V-2_5.yaml
  - openbmb/MiniCPM-S-1B-sft.yaml
  - openbmb/MiniCPM-V-2_6.yaml
  - openbmb/MiniCPM-V-2.yaml
  - openbmb/MiniCPM3-4B.yaml

  # OpenGVLab
  - OpenGVLab/InternVL2_5-4B.yaml
  - OpenGVLab/InternVL2-4B.yaml
  - OpenGVLab/Mono-InternVL-2B.yaml

  # OrionStarAI
  - OrionStarAI/Orion-14B-Base.yaml

  # parasail-ai
  - parasail-ai/GritLM-7B-vllm.yaml

  # peiyi9979
  - peiyi9979/math-shepherd-mistral-7b-prm.yaml

  # Qwen
  - Qwen/QVQ-72B-Preview.yaml
  - Qwen/Qwen-7B-Chat.yaml
  - Qwen/Qwen-7B.yaml
  - Qwen/Qwen-VL-Chat.yaml
  - Qwen/Qwen-VL.yaml
  - Qwen/Qwen1.5-MoE-A2.7B.yaml
  - Qwen/Qwen2-Audio-7B-Instruct.yaml
  - Qwen/Qwen2-VL-2B-Instruct.yaml
  - Qwen/Qwen2-VL-72B-Instruct.yaml
  - Qwen/Qwen2-VL-7B-Instruct.yaml
  - Qwen/Qwen2.5-0.5B.yaml
  - Qwen/Qwen2.5-1.5B.yaml
  - Qwen/Qwen2.5-14B.yaml
  - Qwen/Qwen2.5-32B.yaml
  - Qwen/Qwen2.5-3B.yaml
  - Qwen/Qwen2.5-72B.yaml
  - Qwen/Qwen2.5-7B.yaml
  - Qwen/Qwen2.5-Math-PRM-72B.yaml
  - Qwen/Qwen2.5-Math-PRM-7B.yaml
  - Qwen/Qwen2.5-Math-RM-72B.yaml
  - Qwen/Qwen3-0.6B.yaml
  - Qwen/Qwen3-1.7B.yaml
  - Qwen/Qwen3-14B.yaml
  - Qwen/Qwen3-30B-A3B.yaml
  - Qwen/Qwen3-32B.yaml
  - Qwen/Qwen3-4B.yaml
  - Qwen/Qwen3-8B.yaml
  - Qwen/Qwen3-Embedding-0.6B.yaml
  - Qwen/Qwen3-Embedding-4B.yaml
  - Qwen/Qwen3-Embedding-8B.yaml
  - Qwen/Qwen3-Next-80B-A3B-Instruct.yaml
  - Qwen/Qwen3-VL-235B-A22B-Instruct.yaml
  - Qwen/QwQ-32B-Preview.yaml

  # rednote-hilab
  - rednote-hilab/dots.ocr.yaml
  - rednote-hilab/dots.vlm1.inst.yaml

  # rhymes-ai
  - rhymes-ai/Aria.yaml

  # royokong
  - royokong/e5-v.yaml

  # Salesforce
  - Salesforce/blip2-opt-2.7b.yaml
  - Salesforce/blip2-opt-6.7b.yaml

  # sentence-transformers
  - sentence-transformers/all-roberta-large-v1.yaml

  # Skywork
  - Skywork/Skywork-Reward-Gemma-2-27B-v0.2.yaml
  - Skywork/Skywork-Reward-Llama-3.1-8B-v0.2.yaml

  # Snowflake
  - Snowflake/snowflake-arctic-base.yaml
  - Snowflake/snowflake-arctic-instruct.yaml

  # ssmits
  - ssmits/Qwen2-7B-Instruct-embed-base.yaml

  # stabilityai
  - stabilityai/stablelm-3b-4e1t.yaml
  - stabilityai/stablelm-tuned-alpha-7b.yaml

  # state-spaces
  - state-spaces/mamba-130m-hf.yaml
  - state-spaces/mamba-2.8b-hf.yaml
  - state-spaces/mamba-790m-hf.yaml

  # TeleAI
  - TeleAI/TeleChat2-35B.yaml
  - TeleAI/TeleChat2-3B.yaml
  - TeleAI/TeleChat2-7B.yaml

  # THUDM
  - THUDM/chatglm2-6b.yaml
  - THUDM/chatglm3-6b.yaml
  - THUDM/glm-4v-9b.yaml

  # TIGER-Lab
  - TIGER-Lab/Mantis-8B-siglip-llama3.yaml
  - TIGER-Lab/VLM2Vec-Full.yaml

  # tiiuae
  - tiiuae/falcon-40b.yaml
  - tiiuae/falcon-7b.yaml
  - tiiuae/falcon-mamba-7b.yaml
  - tiiuae/falcon-rw-7b.yaml

  # upstage
  - upstage/SOLAR-10.7B-Instruct-v1.0.yaml
  - upstage/solar-pro-preview-instruct.yaml

  # WizardLM
  - WizardLM/WizardCoder-15B-V1.0.yaml

  # xai-org
  - xai-org/grok-1.yaml

  # XiaomiMiMo
  - XiaomiMiMo/MiMo-7B-RL.yaml
  - XiaomiMiMo/MiMo-VL-7B-RL.yaml

  # xverse
  - xverse/XVERSE-13B-Chat.yaml
  - xverse/XVERSE-65B-Chat.yaml
  - xverse/XVERSE-7B-Chat.yaml
  - xverse/XVERSE-MoE-A36B.yaml

  # zai-org
  - zai-org/GLM-4.5V.yaml

  # ZhipuAI
  - ZhipuAI/glm-4-9b-chat.yaml
