apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: decilm-7b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: deci
  disabled: false
  version: "1.0.0"
  displayName: deci.decilm-7b-instruct
  storage:
    storageUri: hf://Deci/DeciLM-7B-instruct
    path: /raid/models/deci/decilm-7b-instruct
