apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-bigcode-santacoder
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigcode
  disabled: false
  version: "1.0.0"
  displayName: bigcode.gpt-bigcode-santacoder
  storage:
    storageUri: hf://bigcode/gpt_bigcode-santacoder
    path: /raid/models/bigcode/gpt-bigcode-santacoder
