apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: starcoder2-15b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigcode
  disabled: false
  version: "1.0.0"
  displayName: bigcode.starcoder2-15b
  storage:
    storageUri: hf://bigcode/starcoder2-15b
    path: /raid/models/bigcode/starcoder2-15b
