apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: starcoder2-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigcode
  displayName: bigcode.starcoder2-7b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://bigcode/starcoder2-7b
    path: /raid/models/bigcode/starcoder2-7b
