apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: glm-4-9b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: ZhipuAI
  displayName: ZhipuAI.glm-4-9b-chat
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://ZhipuAI/glm-4-9b-chat
    path: /raid/models/ZhipuAI/glm-4-9b-chat
    key: "hf-token"
