apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: vicuna-7b-v1-5
  namespace: vicuna-7b-v1-5
spec:
  model:
    name: vicuna-7b-v1-5
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-vicuna-7b-v1-5
  router:
    minReplicas: 1
    maxReplicas: 1
