apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: chatglm2-6b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: THUDM
  displayName: THUDM.chatglm2-6b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://THUDM/chatglm2-6b
    path: /raid/models/THUDM/chatglm2-6b
