apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: chatglm3-6b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: thudm
  disabled: false
  version: "1.0.0"
  displayName: thudm.chatglm3-6b
  storage:
    storageUri: hf://THUDM/chatglm3-6b
    path: /raid/models/thudm/chatglm3-6b
