apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: glm-4v-9b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: thudm
  disabled: false
  version: "1.0.0"
  displayName: thudm.glm-4v-9b
  storage:
    storageUri: hf://THUDM/glm-4v-9b
    path: /raid/models/thudm/glm-4v-9b
