apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: bge-reranker-v2-m3
  namespace: bge-reranker-v2-m3
spec:
  model:
    name: bge-reranker-v2-m3
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
