---
apiVersion: v1
kind: Namespace
metadata:
  name: phi-4
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: phi-4
  namespace: phi-4
spec:
  model:
    name: phi-4
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
