---
apiVersion: v1
kind: Namespace
metadata:
  name: phi-4-mini-instruct
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: phi-4-mini-instruct
  namespace: phi-4-mini-instruct
spec:
  model:
    name: phi-4-mini-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
