apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-nemotron-nano-8b-v1
  namespace: llama-3-1-nemotron-nano-8b-v1
spec:
  model:
    name: llama-3-1-nemotron-nano-8b-v1
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-llama-3-1-nemotron-nano-8b-v1
  router:
    minReplicas: 1
    maxReplicas: 1
