apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: falcon-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: tiiuae
  disabled: false
  version: "1.0.0"
  displayName: tiiuae.falcon-7b
  storage:
    storageUri: hf://tiiuae/falcon-7b
    path: /raid/models/tiiuae/falcon-7b
