apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: falcon3-10b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: tiiuae
  displayName: falcon3-10b-instruct
  disabled: false
  version: "1.0.0"
  modelArchitecture: LlamaForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.46.1"
  modelParameterSize: 10B
  storage:
    storageUri: hf://tiiuae/Falcon3-10B-Instruct
    path: /raid/models/tiiuae/Falcon3-10B-Instruct
    key: "hf-token"
