apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: stablelm-tuned-alpha-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: stabilityai
  displayName: stabilityai.stablelm-tuned-alpha-7b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://stabilityai/stablelm-tuned-alpha-7b
    path: /raid/models/stabilityai/stablelm-tuned-alpha-7b
