apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: stablelm-2-12b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: stabilityai
  displayName: stabilityai.stablelm-2-12b-chat
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://stabilityai/stablelm-2-12b-chat
    path: /raid/models/stabilityai/stablelm-2-12b-chat
