apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: afm-4-5b-base
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: arcee-ai
  displayName: arcee-ai.afm-4.5b-base
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://arcee-ai/AFM-4.5B-Base
    path: /raid/models/arcee-ai/AFM-4.5B-Base
