apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: aquilachat-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: baai
  disabled: false
  version: "1.0.0"
  displayName: baai.aquilachat-7b
  storage:
    storageUri: hf://BAAI/AquilaChat-7B
    path: /raid/models/baai/aquilachat-7b
