apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: aquila-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: baai
  disabled: false
  version: "1.0.0"
  displayName: baai.aquila-7b
  storage:
    storageUri: hf://BAAI/Aquila-7B
    path: /raid/models/baai/aquila-7b
