apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bge-base-en-v1-5
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  vendor: baai
  disabled: false
  version: "1.0.0"
  displayName: baai.bge-base-en-v1.5
  storage:
    storageUri: hf://BAAI/bge-base-en-v1.5
    path: /raid/models/baai/bge-base-en-v1.5
