apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ome-model-agent-daemonset
  namespace: ome
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: 
      app.kubernetes.io/component: "ome-model-agent-daemonset"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "ome-model-agent-daemonset"
        control-plane: ome-model-agent-daemonset
        logging-forward: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: ome-model-agent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - BM.GPU2.2
                      - BM.GPU3.8
                      - BM.GPU4.8
                      - VM.GPU2.1
                      - VM.GPU3.1
                      - VM.GPU3.2
                      - VM.GPU3.4
                      - BM.GPU.T1.2
                      - BM.GPU.T1-2.4
                      - BM.GPU.A100-v2.8
                      - BM.GPU.GM4.8
                      - BM.GPU.A10.4
                      - BM.GPU.GU1.4
                      - VM.GPU.A10.1
                      - VM.GPU.GU1.1
                      - VM.GPU.A10.2
                      - VM.GPU.GU1.2
                      - BM.GPU.B4.8
                      - BM.GPU.H100.8
                  - key: oci.oraclecloud.com/disable-gpu-device-plugin
                    operator: NotIn
                    values:
                      - 'true'
                  - key: node-role.kubernetes.io/virtual-node
                    operator: DoesNotExist
      volumes:
      - name: host-models
        hostPath:
          path: /raid/models
          type: Directory
      containers:
      - name: model-agent
        image: ko://github.com/sgl-project/ome/cmd/model-agent
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        args:
        - --models-root-dir
        - /raid/models
        - --num-download-worker
        - '2'
        - --concurrency
        - '2'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-models
          readOnly: false
          mountPath: /raid/models
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 20
        resources:
          limits:
            cpu: '10'
            memory: 100Gi
          requests:
            cpu: '10'
            memory: 100Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists  
          effect: NoSchedule
