apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - headless-service.yaml
