apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-v1-5-7b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: llava
  disabled: false
  version: "1.0.0"
  displayName: llava.llava-v1.5-7b
  storage:
    storageUri: hf://liuhaotian/llava-v1.5-7b
    path: /raid/models/llava/llava-v1-5-7b
