apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-v1-5-13b
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: liuhaotian
  displayName: liuhaotian.llava-v1.5-13b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://liuhaotian/llava-v1.5-13b
    path: /raid/models/liuhaotian/llava-v1.5-13b
