apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: falcon-7b-instruct
  namespace: falcon-7b-instruct
spec:
  model:
    name: falcon-7b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-falcon-7b-instruct
  router:
    minReplicas: 1
    maxReplicas: 1
