apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: falcon3-10b-instruct
  namespace: falcon3-10b-instruct
spec:
  model:
    name: falcon3-10b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
