apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bloomz-7b1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigscience
  disabled: false
  version: "1.0.0"
  displayName: bigscience.bloomz-7b1
  storage:
    storageUri: hf://bigscience/bloomz-7b1
    path: /raid/models/bigscience/bloomz-7b1
