apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bloom
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigscience
  disabled: false
  version: "1.0.0"
  displayName: bigscience.bloom
  storage:
    storageUri: hf://bigscience/bloom
    path: /raid/models/bigscience/bloom
