apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bloomz
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: bigscience
  disabled: false
  version: "1.0.0"
  displayName: bigscience.bloomz
  storage:
    storageUri: hf://bigscience/bloomz
    path: /raid/models/bigscience/bloomz
