apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mimo-7b-rl
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: XiaomiMiMo
  displayName: XiaomiMiMo.mimo-7b-rl
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://XiaomiMiMo/MiMo-7B-RL
    path: /raid/models/XiaomiMiMo/MiMo-7B-RL
