apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mimo-vl-7b-rl
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: XiaomiMiMo
  displayName: XiaomiMiMo.mimo-vl-7b-rl
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://XiaomiMiMo/MiMo-VL-7B-RL
    path: /raid/models/XiaomiMiMo/MiMo-VL-7B-RL
