apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mpt-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: mosaicml
  disabled: false
  version: "1.0.0"
  displayName: mosaicml.mpt-7b
  storage:
    storageUri: hf://mosaicml/mpt-7b
    path: /raid/models/mosaicml/mpt-7b
