apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: gpt-oss-20b
  namespace: openai-test
  annotations:
    ome.io/deploymentMode: RawDeployment
spec:
  model:
    name: gpt-oss-20b
  engine:
    minReplicas: 1
    maxReplicas: 1
