apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: skywork-or1-7b-preview
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Skywork
  displayName: skywork-or1-7b-preview
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen2ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.45.2"
  modelParameterSize: 7B
  storage:
    storageUri: hf://Skywork/Skywork-OR1-7B-Preview
    path: /raid/models/Skywork/Skywork-OR1-7B-Preview
    key: "hf-token"
