apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: smollm2-1-7b-instruct
  namespace: smollm2-1-7b-instruct
spec:
  model:
    name: smollm2-1-7b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-smollm2-1-7b-instruct
  router:
    minReplicas: 1
    maxReplicas: 1
