apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-onevision-qwen2-7b-ov
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: lmms-lab
  displayName: lmms-lab.llava-onevision-qwen2-7b-ov
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://lmms-lab/llava-onevision-qwen2-7b-ov
    path: /raid/models/lmms-lab/llava-onevision-qwen2-7b-ov
