apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-next-72b
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: lmms-lab
  displayName: lmms-lab.llava-next-72b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://lmms-lab/llava-next-72b
    path: /raid/models/lmms-lab/llava-next-72b
