apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-next-8b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: lmms
  disabled: false
  version: "1.0.0"
  displayName: lmms.llava-next-8b
  storage:
    storageUri: hf://lmms-lab/llava-next-8b
    path: /raid/models/lmms/llava-next-8b
