apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: snowflake-arctic-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: snowflake
  disabled: false
  version: "1.0.0"
  displayName: snowflake.arctic-instruct
  storage:
    storageUri: hf://Snowflake/snowflake-arctic-instruct
    path: /raid/models/snowflake/snowflake-arctic-instruct
