apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: jet-nemotron-2b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: jet-ai
  displayName: jet-ai.jet-nemotron-2b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://jet-ai/Jet-Nemotron-2B
    path: /raid/models/jet-ai/Jet-Nemotron-2B
    key: "hf-token"
