apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-oss-20b
spec:
  vendor: openai
  disabled: false
  version: "1.0.0"
  displayName: openai.gpt-oss-20b
  modelCapabilities:
    - "CHAT"
  modelFramework:
    name: transformers
    version: "4.55.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelArchitecture: GptOssForCausalLM
  storage:
    storageUri: hf://openai/gpt-oss-20b
    path: /raid/models/openai/gpt-oss-20b