apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: minimax-m2
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: minimax
  displayName: minimax.minimax-m2
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://minimax/MiniMax-M2
    path: /raid/models/minimax/MiniMax-M2
    key: "hf-token"
