apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: skywork-or1-7b-preview
  namespace: skywork-or1-7b-preview
spec:
  model:
    name: skywork-or1-7b-preview
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
