apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: xverse-65b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: xverse
  disabled: false
  version: "1.0.0"
  displayName: xverse.xverse-65b-chat
  storage:
    storageUri: hf://xverse/XVERSE-65B-Chat
    path: /raid/models/xverse/xverse-65b-chat
