apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: xverse-moe-a36b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: xverse
  displayName: xverse.xverse-moe-a36b
  disabled: false
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.30.0"
  modelArchitecture: XverseMoeForCausalLM
  storage:
    storageUri: hf://xverse/XVERSE-MoE-A36B
    path: /raid/models/xverse/XVERSE-MoE-A36B
