hiddenMemberFields:
  - "TypeMeta"
  - "ObjectMeta"

apis:
  - name: ome
    title: OME API
    package: github.com/sgl-project/ome
    path: pkg/apis/ome/v1beta1

externalPackages:
  - match: ^k8s\.io/(api|apimachinery/pkg/apis)/
    target: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#{{- lower .TypeIdentifier -}}-{{- arrIndex .PackageSegments -1 -}}-{{- arrIndex .PackageSegments -2 -}}
  - match: ^k8s\.io/apimachinery/pkg/api/resource\.Quantity$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity
  - match: ^k8s.io/component-base/config/v1alpha1.
    target: https://pkg.go.dev/k8s.io/component-base/config/v1alpha1#{{- .TypeIdentifier -}}
  - match: ^time\.Duration$
    target: https://pkg.go.dev/time#Duration
  - match: ^github\.com/kedacore/keda/v2/apis/keda/v1alpha1\.
    target: https://pkg.go.dev/github.com/kedacore/keda/v2/apis/keda/v1alpha1#{{- .TypeIdentifier -}}
  - match: ^istio\.io/api/networking/v1beta1\.
    target: https://pkg.go.dev/istio.io/api/networking/v1beta1#{{- .TypeIdentifier -}}
  - match: ^knative\.dev/pkg/apis/duck/v1\.
    target: https://pkg.go.dev/knative.dev/pkg/apis/duck/v1#{{- .TypeIdentifier -}}
  - match: ^knative\.dev/serving/pkg/apis/serving/v1\.
    target: https://pkg.go.dev/knative.dev/serving/pkg/apis/serving/v1#{{- .TypeIdentifier -}}
  - match: ^sigs\.k8s\.io/gateway-api/apis/v1\.
    target: https://pkg.go.dev/sigs.k8s.io/gateway-api/apis/v1#{{- .TypeIdentifier -}}
  - match: ^volcano\.sh/apis/batch/v1alpha1\.
    target: https://pkg.go.dev/volcano.sh/apis/batch/v1alpha1#{{- .TypeIdentifier -}}
  - match: ^k8s\.io/apimachinery/pkg/runtime\.RawExtension$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#RawExtension
  - match: ^knative\.dev/pkg/apis\.URL$
    target: https://pkg.go.dev/knative.dev/pkg/apis#URL
  - match: ^github\.com/sgl-project/sgl-ome/pkg/constants\.
    target: https://pkg.go.dev/github.com/sgl-project/ome/pkg/constants#{{- .TypeIdentifier -}}