apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: gme-qwen2-vl-2b-instruct
spec:
  model:
    name: gme-qwen2-vl-2b-instruct
  runtime:
    name: srt-gme-qwen2-vl-2b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
