apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-3-5-moe-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: microsoft
  displayName: microsoft.phi-3.5-moe-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://microsoft/Phi-3.5-MoE-instruct
    path: /raid/models/microsoft/Phi-3.5-MoE-instruct
