apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-3-mini-128k-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: microsoft
  disabled: false
  version: "1.0.0"
  displayName: microsoft.phi-3-mini-128k-instruct
  storage:
    storageUri: hf://microsoft/Phi-3-mini-128k-instruct
    path: /raid/models/microsoft/phi-3-mini-128k-instruct
