apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-4
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: microsoft
  disabled: false
  version: "1.0.0"
  displayName: microsoft.phi-4
  storage:
    storageUri: hf://microsoft/phi-4
    path: /raid/models/microsoft/phi-4
