apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-4-mini-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: microsoft
  disabled: false
  version: "1.0.0"
  displayName: microsoft.phi-4-mini-instruct
  storage:
    storageUri: hf://microsoft/Phi-4-mini-instruct
    path: /raid/models/microsoft/Phi-4-mini-instruct
