apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: phi-1-5
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: microsoft
  disabled: false
  version: "1.0.0"
  displayName: microsoft.phi-1.5
  storage:
    storageUri: hf://microsoft/phi-1_5
    path: /raid/models/microsoft/phi-1-5
