apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: baichuan2-13b-chat
  namespace: baichuan2-13b-chat
spec:
  model:
    name: baichuan2-13b-chat
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-baichuan2-13b-chat
  router:
    minReplicas: 1
    maxReplicas: 1
