{{- if index .Values "llama-3-3-70b-instruct-ft" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-3-70b-instruct-ft
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/category: "LARGE"
    models.ome.io/experimental: "{{ index .Values "llama-3-3-70b-instruct-ft" "isExperimental" }}"
    models.ome.io/internal: "{{ index .Values "llama-3-3-70b-instruct-ft" "isInternal" }}"
    models.ome.io/lifecycle-phase: "{{ index .Values "llama-3-3-70b-instruct-ft" "lifecyclePhase" }}"
    models.ome.io/training-runtime: "llama-3-3-70b-instruct-ft"
spec:
  compartmentID: {{ .Values.compartmentID }}
  disabled: false
  displayName: meta.llama-3.3-70b-instruct
  storage:
    storageUri: "oci://n/{{ .Values.osnamespace }}/b/{{ index .Values "llama-3-3-70b-instruct-ft" "osBucket" }}/o/{{ index .Values "llama-3-3-70b-instruct-ft" "vendor" }}/{{ index .Values "llama-3-3-70b-instruct-ft" "osPrefixOverride" }}"
    path: /mnt/data/models/meta/llama-3-3-70b-instruct
  vendor: meta
  version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.47.0.dev0"
  modelFormat:
    name: safetensors
    version: "1"
  modelArchitecture: LlamaForCausalLM
  modelParameterSize: 70B
  modelCapabilities:
    - "CHAT"
  maxTokens: 131072
  additionalMetadata:
    type: "Finetuning"
    internalName: "llama-3-3-70b-instruct"
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: LARGE_GENERIC
          quotaUnit: 2
          default: true
  modelConfiguration:
    {
      "architectures": [
        "LlamaForCausalLM"
      ],
      "attention_bias": false,
      "attention_dropout": 0.0,
      "bos_token_id": 128000,
      "eos_token_id": [
        128001,
        128008,
        128009
      ],
      "head_dim": 128,
      "hidden_act": "silu",
      "hidden_size": 8192,
      "initializer_range": 0.02,
      "intermediate_size": 28672,
      "max_position_embeddings": 131072,
      "mlp_bias": false,
      "model_type": "llama",
      "num_attention_heads": 64,
      "num_hidden_layers": 80,
      "num_key_value_heads": 8,
      "pretraining_tp": 1,
      "rms_norm_eps": 1e-05,
      "rope_scaling": {
        "factor": 8.0,
        "high_freq_factor": 4.0,
        "low_freq_factor": 1.0,
        "original_max_position_embeddings": 8192,
        "rope_type": "llama3"
      },
      "rope_theta": 500000.0,
      "tie_word_embeddings": false,
      "torch_dtype": "bfloat16",
      "transformers_version": "4.47.0.dev0",
      "use_cache": true,
      "vocab_size": 128256
    }
{{- end }}