apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: h2ovl-mississippi-800m
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: h2oai
  disabled: false
  version: "1.0.0"
  displayName: h2oai.h2ovl-mississippi-800m
  storage:
    storageUri: hf://h2oai/h2ovl-mississippi-800m
    path: /raid/models/h2oai/h2ovl-mississippi-800m
