apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: xgen-7b-8k-inst
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Salesforce
  disabled: false
  version: "1.0.0"
  displayName: Salesforce.xgen-7b-8k-inst
  modelFormat:
    name: pytorch
    version: "1.0.0"
  storage:
    storageUri: hf://Salesforce/xgen-7b-8k-inst
    path: /raid/models/Salesforce/xgen-7b-8k-inst
