apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: jet-nemotron-2b
  namespace: jet-nemotron-2b
spec:
  model:
    name: jet-nemotron-2b
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-jet-nemotron-2b
  router:
    minReplicas: 1
    maxReplicas: 1
