apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gritlm-7b-vllm
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
    - TEXT_TO_EMBEDDING
  vendor: parasail
  disabled: false
  version: "1.0.0"
  displayName: parasail.gritlm-7b-vllm
  storage:
    storageUri: hf://parasail-ai/GritLM-7B-vllm
    path: /raid/models/parasail/gritlm-7b-vllm
