apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: glm-4-5v
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: zai-org
  displayName: zai-org.glm-4.5v
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://zai-org/GLM-4.5V
    path: /raid/models/zai-org/GLM-4.5V
    key: hf-token
