apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: yi-34b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: 01-ai
  disabled: false
  version: "1.0.0"
  displayName: 01-ai.yi-34b
  storage:
    storageUri: hf://01-ai/Yi-34B
    path: /raid/models/01-ai/yi-34b
