apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: deepseek-v3
  namespace: deepseek-v3
spec:
  model:
    name: deepseek-v3
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-deepseek-v3
  router:
    minReplicas: 1
    maxReplicas: 1
