apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: deepseek-r1-distill-qwen-7b
  namespace: deepseek-r1-distill-qwen-7b
spec:
  model:
    name: deepseek-r1-distill-qwen-7b
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-deepseek-r1-distill-qwen-7b
  router:
    minReplicas: 1
    maxReplicas: 1
