apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: deepseek-coder-7b-instruct-v1-5
  namespace: deepseek-coder-7b-instruct
spec:
  model:
    name: deepseek-coder-7b-instruct-v1-5
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-deepseek-coder-7b-instruct-v1-5
  router:
    minReplicas: 1
    maxReplicas: 1
