apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: janus-pro-7b-test
  namespace: janus-pro-7b-test
spec:
  model:
    name: janus-pro-7b
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-janus-pro-7b
  router:
    minReplicas: 1
    maxReplicas: 1
