apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: ernie-4-5-21b-a3b-pt
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: baidu
  displayName: baidu.ernie-4.5-21b-a3b-pt
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://baidu/ERNIE-4.5-21B-A3B-PT
    path: /raid/models/baidu/ERNIE-4.5-21B-A3B-PT
