apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: unsloth-llama-3-2-11b-vision-instruct
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: unsloth
  displayName: unsloth.llama-3.2-11b-vision-instruct
  disabled: false
  version: "1.0.0"
  modelArchitecture: MllamaForConditionalGeneration
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.46.3"
  modelParameterSize: 11B
  storage:
    storageUri: hf://unsloth/Llama-3.2-11B-Vision-Instruct
    path: /raid/models/unsloth/Llama-3.2-11B-Vision-Instruct
    key: "hf-token"
