apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: dots-ocr
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: rednote-hilab
  displayName: rednote-hilab.dots.ocr
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://rednote-hilab/dots.ocr
    path: /raid/models/rednote-hilab/dots.ocr
