apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: dots-vlm1-inst
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: rednote-hilab
  displayName: rednote-hilab.dots.vlm1.inst
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://rednote-hilab/dots.vlm1.inst
    path: /raid/models/rednote-hilab/dots.vlm1.inst
