apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: smollm2-1-7b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: HuggingFaceTB
  displayName: HuggingFaceTB.SmolLM2-1.7B-Instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://HuggingFaceTB/SmolLM2-1.7B-Instruct
    path: /raid/models/HuggingFaceTB/SmolLM2-1.7B-Instruct
    key: "hf-token"
