apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: smollm-360m
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: huggingface
  disabled: false
  version: "1.0.0"
  displayName: huggingface.smollm-360m
  storage:
    storageUri: hf://HuggingFaceTB/SmolLM-360M
    path: /raid/models/huggingface/smollm-360m
