apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: smollm-1-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: HuggingFaceTB
  displayName: HuggingFaceTB.smollm-1.7b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://HuggingFaceTB/SmolLM-1.7B
    path: /raid/models/HuggingFaceTB/SmolLM-1.7B
