apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: exaone-3-5-7-8b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: LGAI-EXAONE
  displayName: LGAI-EXAONE.exaone-3.5-7.8b-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct
    path: /raid/models/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct
