apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: e5-mistral-7b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  disabled: false
  displayName: intfloat.e5-mistral-7b-instruct
  storage:
    storageUri: hf://intfloat/e5-mistral-7b-instruct
    path: /raid/models/intfloat/e5-mistral-7b-instruct
    key: "hf-token"
  vendor: intfloat
  version: "1.0.0"