apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-7b-instruct-v0-2
spec:
  model:
    name: mistral-7b-instruct-v0-2
  runtime:
    name: srt-mistral-7b-instruct-v0-2
  engine:
    minReplicas: 0
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
