apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-small-3-1-24b-instruct-2503
spec:
  model:
    name: mistral-small-3-1-24b-instruct-2503
  runtime:
    name: srt-mistral-small-3-1-24b-instruct-2503
  engine:
    minReplicas: 0
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
