apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-7b-instruct-v0-2
spec:
  baseModelRef:
    name: mistral-7b-instruct-v0-2
  runtimeRef:
    name: srt-mistral-7b-instruct-v0-2
  scalingConfig:
    minReplicas: 0
    maxReplicas: 1
