apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-nemo-instruct-2407
  namespace: mistral-nemo-instruct-2407
spec:
  model:
    name: mistral-nemo-instruct-2407
  runtime:
    name: srt-mistral-nemo-instruct-2407
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
