apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: jais-13b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: inceptionai
  disabled: false
  version: "1.0.0"
  displayName: inceptionai.jais-13b
  storage:
    storageUri: hf://inceptionai/jais-13b
    path: /raid/models/inceptionai/jais-13b
