apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: kimi-vl-a3b-instruct
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
  vendor: moonshotai
  displayName: moonshotai.kimi-vl-a3b-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://moonshotai/Kimi-VL-A3B-Instruct
    path: /raid/models/moonshotai/Kimi-VL-A3B-Instruct
