apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: kimi-k2-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: moonshotai
  displayName: moonshotai.kimi-k2-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://moonshotai/Kimi-K2-Instruct
    path: /raid/models/moonshotai/Kimi-K2-Instruct