---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-3-1-405b-instruct-fp8
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-405b-instruct-fp8
  namespace: llama-3-1-405b-instruct-fp8
spec:
  model:
    name: llama-3-1-405b-instruct-fp8
  runtime:
    name: srt-llama-3-1-405b-instruct-fp8
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1