apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-2-7b
  namespace: llama-2-7b
spec:
  model:
    name: llama-2-7b
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
