apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-8b-instruct
  namespace: llama-3-8b-instruct
spec:
  model:
    name: llama-3-8b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-llama-3-8b-instruct
  router:
    minReplicas: 1
    maxReplicas: 1
