apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bart-large-cnn
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: facebook
  disabled: false
  version: "1.0.0"
  displayName: facebook.bart-large-cnn
  storage:
    storageUri: hf://facebook/bart-large-cnn
    path: /raid/models/facebook/bart-large-cnn
