apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: bart-base
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: facebook
  disabled: false
  version: "1.0.0"
  displayName: facebook.bart-base
  storage:
    storageUri: hf://facebook/bart-base
    path: /raid/models/facebook/bart-base
