apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: chameleon-7b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: facebook
  disabled: false
  version: "1.0.0"
  displayName: facebook.chameleon-7b
  storage:
    storageUri: hf://facebook/chameleon-7b
    path: /raid/models/facebook/chameleon-7b
