apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: opt-iml-max-30b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: facebook
  disabled: false
  version: "1.0.0"
  displayName: facebook.opt-iml-max-30b
  storage:
    storageUri: hf://facebook/opt-iml-max-30b
    path: /raid/models/facebook/opt-iml-max-30b
