apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: opt-66b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: facebook
  disabled: false
  version: "1.0.0"
  displayName: facebook.opt-66b
  storage:
    storageUri: hf://facebook/opt-66b
    path: /raid/models/facebook/opt-66b
