apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-nemotron-nano-8b-v1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: nvidia
  disabled: false
  version: "1.0.0"
  displayName: nvidia.llama-3.1-nemotron-nano-8b-v1
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.47.1"
  modelArchitecture: LlamaForCausalLM
  storage:
    storageUri: hf://nvidia/Llama-3.1-Nemotron-Nano-8B-v1
    path: /raid/models/nvidia/llama-3-1-nemotron-nano-8b-v1
    key: "hf-token"