apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-3-nemotron-super-49b-v1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  disabled: false
  displayName: nvidia.Llama-3.3-Nemotron-Super-49B-v1
  vendor: nvidia
  version: "1.0.0"
  storage:
    storageUri: hf://nvidia/Llama-3.3-Nemotron-Super-49B-v1
    path: /raid/models/nvidia/Llama-3.3-Nemotron-Super-49B-v1
