apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-nemotron-70b-instruct-hf
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: nvidia
  displayName: nvidia.Llama-3.1-Nemotron-70B-Instruct-HF
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
    path: /raid/models/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
