apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: nvidia-nemotron-nano-12b-v2-vl-bf16
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: nvidia
  displayName: nvidia.nvidia-nemotron-nano-12b-v2-vl-bf16
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16
    path: /raid/models/nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16
