apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: nvidia-nemotron-3-nano-30b-a3b-fp8
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: nvidia
  disabled: false
  version: "1.0.0"
  displayName: nvidia.NVIDIA-Nemotron-3-Nano-30B-A3B-FP8
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.53.2"
  modelArchitecture: NemotronHForCausalLM
  storage:
    storageUri: hf://nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8
    path: /raid/models/nvidia/nvidia-nemotron-3-nano-30b-a3b-fp8
    key: "hf-token"
