apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: nvlm-d-72b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: nvidia
  disabled: false
  version: "1.0.0"
  displayName: nvidia.nvlm-d-72b
  storage:
    storageUri: hf://nvidia/NVLM-D-72B
    path: /raid/models/nvidia/nvlm-d-72b
