apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: ling-plus
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: inclusionAI
  displayName: inclusionAI.ling-plus
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://inclusionAI/Ling-plus
    path: /raid/models/inclusionAI/Ling-plus
