apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: math-shepherd-mistral-7b-prm
spec:
  modelCapabilities:
    - REWARD_SCORING
  vendor: peiyi9979
  disabled: false
  version: "1.0.0"
  displayName: peiyi9979.math-shepherd-mistral-7b-prm
  storage:
    storageUri: hf://peiyi9979/math-shepherd-mistral-7b-prm
    path: /raid/models/peiyi9979/math-shepherd-mistral-7b-prm
