apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: fuyu-8b
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: adept
  disabled: false
  version: "1.0.0"
  displayName: adept.fuyu-8b
  storage:
    storageUri: hf://adept/fuyu-8b
    path: /raid/models/adept/fuyu-8b
