apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- full/ome.io_inferenceservices.yaml
- full/ome.io_clusterservingruntimes.yaml
- full/ome.io_servingruntimes.yaml
- full/ome.io_basemodels.yaml
- full/ome.io_clusterbasemodels.yaml
- full/ome.io_finetunedweights.yaml
- full/ome.io_benchmarkjobs.yaml
- full/ome.io_acceleratorclasses.yaml

patches:
# Fix for https://github.com/kubernetes/kubernetes/issues/91395
- path: patches/protocol.yaml
  target:
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
    name: inferenceservices.ome.io

# Work around for https://github.com/kubernetes-sigs/kustomize/issues/5031. Can be removed once the issue is fixed.
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: inferenceservices.ome.io
