apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: orion-14b-base
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: OrionStarAI
  displayName: OrionStarAI.orion-14b-base
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://OrionStarAI/Orion-14B-Base
    path: /raid/models/OrionStarAI/Orion-14B-Base
