apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: olmoe-1b-7b-0924
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: allenai
  displayName: allenai.olmoe-1b-7b-0924
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://allenai/OLMoE-1B-7B-0924
    path: /raid/models/allenai/OLMoE-1B-7B-0924
