apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: olmo-7b-hf
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: allenai
  disabled: false
  version: "1.0.0"
  displayName: allenai.olmo-7b-hf
  storage:
    storageUri: hf://allenai/OLMo-7B-hf
    path: /raid/models/allenai/olmo-7b-hf
