apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: olmo-1b-hf
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: allenai
  disabled: false
  version: "1.0.0"
  displayName: allenai.olmo-1b-hf
  storage:
    storageUri: hf://allenai/OLMo-1B-hf
    path: /raid/models/allenai/olmo-1b-hf
