apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: olmo-2-1124-7b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: allenai
  displayName: allenai.olmo-2-1124-7b-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://allenai/OLMo-2-1124-7B-Instruct
    path: /raid/models/allenai/OLMo-2-1124-7B-Instruct
