apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ome.io_inferenceservices.yaml
  - ome.io_clusterservingruntimes.yaml
  - ome.io_servingruntimes.yaml
  - ome.io_basemodels.yaml
  - ome.io_clusterbasemodels.yaml
  - ome.io_dedicatedaiclusters.yaml
  - ome.io_dedicatedaiclusterprofiles.yaml
  - ome.io_capacityreservations.yaml
  - ome.io_clustercapacityreservations.yaml
  - ome.io_clustertrainingruntimes.yaml
  - ome.io_trainingruntimes.yaml
  - ome.io_trainingjobs.yaml
  - ome.io_benchmarkjobs.yaml