apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: dbrx-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: databricks
  displayName: databricks.dbrx-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://databricks/dbrx-instruct
    path: /raid/models/databricks/dbrx-instruct
