apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: dolly-v2-12b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: databricks
  displayName: databricks.dolly-v2-12b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://databricks/dolly-v2-12b
    path: /raid/models/databricks/dolly-v2-12b
    key: "hf-token"
