apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: deepseek-v3
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: deepseek-ai
  displayName: deepseek-ai.deepseek-v3
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://deepseek-ai/DeepSeek-V3
    path: /raid/models/deepseek-ai/deepseek-v3