apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: deepseek-llm-7b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: deepseek
  disabled: false
  version: "1.0.0"
  displayName: deepseek.deepseek-llm-7b-chat
  storage:
    storageUri: hf://deepseek-ai/deepseek-llm-7b-chat
    path: /raid/models/deepseek/deepseek-llm-7b-chat
