apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: deepseek-v2-lite-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: deepseek
  disabled: false
  version: "1.0.0"
  displayName: deepseek.deepseek-v2-lite-chat
  storage:
    storageUri: hf://deepseek-ai/DeepSeek-V2-Lite-Chat
    path: /raid/models/deepseek/DeepSeek-V2-Lite-Chat
