apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: deepseek-r1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: deepseek-ai
  displayName: deepseek-ai.deepseek-r1
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://deepseek-ai/DeepSeek-R1
    path: /raid/models/deepseek-ai/deepseek-r1