apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mistral-nemo-instruct-2407
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: mistral
  disabled: false
  version: "1.0.0"
  displayName: mistral.mistral-nemo-instruct-2407
  storage:
    storageUri: hf://mistralai/Mistral-Nemo-Instruct-2407
    path: /raid/models/mistral/mistral-nemo-instruct-2407
