apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mistral-7b-instruct-v0-2
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: mistralai
  displayName: mistralai.mistral-7b-instruct-v0.2
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://mistralai/Mistral-7B-Instruct-v0.2
    path: /raid/models/mistralai/Mistral-7B-Instruct-v0.2
