apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mixtral-8x7b-instruct-v0-1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: mistral
  disabled: false
  version: "1.0.0"
  displayName: mistral.mixtral-8x7b-instruct-v0.1
  storage:
    storageUri: hf://mistralai/Mixtral-8x7B-Instruct-v0.1
    path: /raid/models/mistral/mixtral-8x7b-instruct-v0-1
