apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: pixtral-12b-2409
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: mistral
  disabled: false
  version: "1.0.0"
  displayName: mistral.pixtral-12b-2409
  storage:
    storageUri: hf://mistralai/Pixtral-12B-2409
    path: /raid/models/mistral/pixtral-12b-2409
