apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-32b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen3-32b
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen3ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.51.0"
  modelParameterSize: 32B
  storage:
    storageUri: hf://Qwen/Qwen3-32B
    path: /raid/models/Qwen/Qwen3-32B
    key: "hf-token"
