apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-30b-a3b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: Qwen.qwen3-30b-a3b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen3-30B-A3B
    path: /raid/models/Qwen/Qwen3-30B-A3B
