apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen-7b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen-7b-chat
  storage:
    storageUri: hf://Qwen/Qwen-7B-Chat
    path: /raid/models/qwen/qwen-7b-chat
