apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-5-vl-7b-instruct
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen2.5-vl-7b-instruct
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen2_5_VLForConditionalGeneration
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.41.2"
  modelParameterSize: 7B
  storage:
    storageUri: hf://Qwen/Qwen2.5-VL-7B-Instruct
    path: /raid/models/Qwen/Qwen2.5-VL-7B-Instruct
    key: "hf-token"
