apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen-7b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen-7b-chat
  disabled: false
  version: "1.0.0"
  modelArchitecture: QWenLMHeadModel
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.32.0"
  modelParameterSize: 7B
  storage:
    storageUri: hf://Qwen/Qwen-7B-Chat
    path: /raid/models/Qwen/Qwen-7B-Chat
    key: "hf-token"
