apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-embedding-4b
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  vendor: Qwen
  displayName: Qwen.qwen3-embedding-4b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen3-Embedding-4B
    path: /raid/models/Qwen/Qwen3-Embedding-4B
