apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-audio-7b-instruct
spec:
  modelCapabilities:
    - AUDIO_TO_TEXT
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen2-audio-7b-instruct
  storage:
    storageUri: hf://Qwen/Qwen2-Audio-7B-Instruct
    path: /raid/models/qwen/qwen2-audio-7b-instruct
