apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-embedding-0-6b
spec:
  modelCapabilities:
    - TEXT_TO_EMBEDDING
  vendor: Qwen
  displayName: Qwen.qwen3-embedding-0.6b
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen3ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.51.3"
  modelParameterSize: 0.6B
  storage:
    storageUri: hf://Qwen/Qwen3-Embedding-0.6B
    path: /raid/models/Qwen/Qwen3-Embedding-0.6B
    key: "hf-token"
