apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen-7b
  storage:
    storageUri: hf://Qwen/Qwen-7B
    path: /raid/models/qwen/qwen-7b
