apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-5-math-prm-7b
spec:
  modelCapabilities:
    - REWARD_SCORING
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen2.5-math-prm-7b
  storage:
    storageUri: hf://Qwen/Qwen2.5-Math-PRM-7B
    path: /raid/models/qwen/qwen2.5-math-prm-7b
