apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-vl-7b-instruct
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen2-vl-7b-instruct
  storage:
    storageUri: hf://Qwen/Qwen2-VL-7B-Instruct
    path: /raid/models/qwen/qwen2-vl-7b-instruct
