apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-5-3b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen2.5-3b-instruct
  storage:
    storageUri: hf://Qwen/Qwen2.5-3B-Instruct
    path: /raid/models/qwen/qwen2-5-3b-instruct
