apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-1-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen3-1.7b
  storage:
    storageUri: hf://Qwen/Qwen3-1.7B
    path: /raid/models/qwen/qwen3-1-7b
