apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-0-6b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: Qwen.qwen3-0.6b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen3-0.6B
    path: /raid/models/Qwen/Qwen3-0.6B
