apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-8b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen3-8b
  storage:
    storageUri: hf://Qwen/Qwen3-8B
    path: /raid/models/qwen/qwen3-8b
