apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-5-coder-32b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen2.5-coder-32b-instruct
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen2ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.43.1"
  modelParameterSize: 32B
  storage:
    storageUri: hf://Qwen/Qwen2.5-Coder-32B-Instruct
    path: /raid/models/Qwen/Qwen2.5-Coder-32B-Instruct
    key: "hf-token"
