apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen-vl
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen-vl
  storage:
    storageUri: hf://Qwen/Qwen-VL
    path: /raid/models/qwen/qwen-vl
