apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-next-80b-a3b-instruct
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: Qwen.qwen3-next-80b-a3b-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen3-Next-80B-A3B-Instruct
    path: /raid/models/Qwen/Qwen3-Next-80B-A3B-Instruct
