apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen-image
spec:
  modelCapabilities:
    - TEXT_TO_IMAGE
  vendor: Qwen
  displayName: qwen.qwen-image
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen-Image
    path: /raid/models/Qwen/Qwen-Image
    key: "hf-token"
