apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-vl-235b-a22b-instruct
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: Qwen
  displayName: Qwen.qwen3-vl-235b-a22b-instruct
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://Qwen/Qwen3-VL-235B-A22B-Instruct
    path: /raid/models/Qwen/Qwen3-VL-235B-A22B-Instruct
