apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen1-5-72b-chat
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen1-5-72b-chat
  disabled: false
  version: "1.0.0"
  modelArchitecture: Qwen2ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.41.2"
  modelParameterSize: 72B
  storage:
    storageUri: hf://Qwen/Qwen1.5-72B-Chat
    path: /raid/models/Qwen/Qwen1.5-72B-Chat
    key: "hf-token"
