apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen1-5-moe-a2-7b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwen1.5-moe-a2.7b
  storage:
    storageUri: hf://Qwen/Qwen1.5-MoE-A2.7B
    path: /raid/models/qwen/qwen1.5-moe-a2.7b
