apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwq-32b-preview
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: qwen
  disabled: false
  version: "1.0.0"
  displayName: qwen.qwq-32b-preview
  storage:
    storageUri: hf://Qwen/QwQ-32B-Preview
    path: /raid/models/qwen/qwq-32b-preview
