# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: solar-10-7b-instruct-v1-0
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: solar-10-7b-instruct-v1-0
  namespace: solar-10-7b-instruct-v1-0
spec:
  model:
    name: solar-10-7b-instruct-v1-0
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-solar-10-7b-instruct-v1-0
  router:
    minReplicas: 1
    maxReplicas: 1
