apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: minicpm3-4b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: openbmb
  displayName: openbmb.minicpm3-4b
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://openbmb/MiniCPM3-4B
    path: /raid/models/openbmb/MiniCPM3-4B
