apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: minicpm-s-1b-sft
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: openbmb
  disabled: false
  version: "1.0.0"
  displayName: openbmb.minicpm-s-1b-sft
  storage:
    storageUri: hf://openbmb/MiniCPM-S-1B-sft
    path: /raid/models/openbmb/minicpm-s-1b-sft
