apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llava-v1-6-mistral-7b-hf
spec:
  modelCapabilities:
    - IMAGE_TO_TEXT
    - TEXT_TO_TEXT
  vendor: llava-hf
  disabled: false
  version: "1.0.0"
  displayName: llava-hf.llava-v1.6-mistral-7b-hf
  storage:
    storageUri: hf://llava-hf/llava-v1.6-mistral-7b-hf
    path: /raid/models/llava-hf/llava-v1.6-mistral-7b-hf
