---
apiVersion: v1
kind: Namespace
metadata:
  name: dolly-v2-12b-test
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: dolly-v2-12b-test
  namespace: dolly-v2-12b-test
spec:
  # model is required, if kind is not specified, the controller will automatically use ClusterBaseModel
  model:
    name: dolly-v2-12b
  # runtime is optional, if not specified, the controller will automatically select a compatible runtime
  # otherwise, please ensure that the runtime is compatible with the model and actually exists
  runtime:
    name: srt-dolly-v2-12b
  engine:
    minReplicas: 1
    maxReplicas: 1
