apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-oss-20b-bf16
spec:
  vendor: openai
  disabled: false
  version: "1.0.0"
  displayName: openai.gpt-oss-20b-bf16
  modelCapabilities:
    - TEXT_TO_TEXT
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.55.1"
  modelArchitecture: GptOssForCausalLM
  storage:
    storageUri: hf://lmsys/gpt-oss-20b-bf16
    path: /raid/models/lmsys/gpt-oss-20b-bf16
    key: "hf-token"