apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-oss-120b-bf16
spec:
  vendor: openai
  disabled: false
  version: "1.0.0"
  displayName: openai.gpt-oss-120b-bf16
  modelCapabilities:
    - TEXT_TO_TEXT
  storage:
    storageUri: hf://lmsys/gpt-oss-120b-bf16
    path: /raid/models/lmsys/gpt-oss-120b-bf16