apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: vicuna-13b-v1-5
spec:
  vendor: lmsys
  disabled: false
  version: "1.0.0"
  displayName: lmsys.vicuna-13b-v1.5
  modelCapabilities:
    - TEXT_TO_TEXT
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.55.1"
  modelArchitecture: LlamaForCausalLM
  storage:
    storageUri: hf://lmsys/vicuna-13b-v1.5
    path: /raid/models/lmsys/vicuna-13b-v1-5
