apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: c4ai-command-r7b-12-2024
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: cohere
  disabled: false
  version: "1.0.0"
  displayName: cohere.c4ai-command-r7b-12-2024
  storage:
    storageUri: hf://CohereForAI/c4ai-command-r7b-12-2024
    path: /raid/models/cohere/c4ai-command-r7b-12-2024
