apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: c4ai-command-r-v01
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: CohereForAI
  displayName: CohereForAI.c4ai-command-r-v01
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://CohereForAI/c4ai-command-r-v01
    path: /raid/models/CohereForAI/c4ai-command-r-v01
