apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-5-coder-7b-instruct
  namespace: qwen2-5-coder-7b-instruct
spec:
  model:
    name: qwen2-5-coder-7b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-qwen2-5-coder-7b-instruct
  router:
    minReplicas: 1
    maxReplicas: 1
