apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen1-5-32b-chat
  namespace: qwen1-5-32b-chat
spec:
  model:
    name: qwen1-5-32b-chat
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
