apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-5-3b
  namespace: qwen2-5-3b
spec:
  model:
    name: qwen2-5-3b
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-qwen2-5-3b
  router:
    minReplicas: 1
    maxReplicas: 1
