apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-32b
  namespace: qwen3-32b
spec:
  model:
    name: qwen3-32b
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
