apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-5-3b-instruct
  namespace: qwen2-5-3b-instruct
spec:
  model:
    name: qwen2-5-3b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
