apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: tele-flm
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: CofeAI
  displayName: CofeAI.tele-flm
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://CofeAI/Tele-FLM
    path: /raid/models/CofeAI/Tele-FLM
