apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: jamba-tiny-reward-dev
spec:
  modelCapabilities:
    - REWARD_SCORING
  vendor: ai21labs
  disabled: false
  version: "1.0.0"
  displayName: ai21labs.jamba-tiny-reward-dev
  storage:
    storageUri: hf://ai21labs/Jamba-tiny-reward-dev
    path: /raid/models/ai21labs/jamba-tiny-reward-dev
