apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: grok-2
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: xai-org
  displayName: xai-org.grok-2
  disabled: false
  version: "1.0.0"
  modelArchitecture: Grok1ForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.35.0"
  modelParameterSize: 314B
  storage:
    storageUri: hf://xai-org/grok-2
    path: /raid/models/xai-org/grok-2
    key: "hf-token"
