apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: grok-1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: xai-org
  displayName: xai-org.grok-1
  disabled: false
  version: "1.0.0"
  storage:
    storageUri: hf://xai-org/grok-1
    path: /raid/models/xai-org/grok-1
