apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: grok-1
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
  vendor: xai-org
  displayName: xai-org.grok-1
  disabled: false
  version: "1.0.0"
  modelArchitecture: Grok1ModelForCausalLM
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.35.0"
  storage:
    storageUri: hf://xai-org/grok-1
    path: /raid/models/xai-org/grok-1
    key: "hf-token"
